BOARD_WIDTH = BOARD_HEIGHT = 512
DIMENSION = 8
SQ_SIZE = BOARD_HEIGHT // DIMENSION
MAX_FPS = 15
IMAGES = {}
WHITE_POV = True
LIGHT_SQUARE_COLOR = "ivory"  # TODO more colors
DARK_SQUARE_COLOR = "dark green"
